name 'puppet-ispconfig'
version '0.0.2'
author 'meth'
license 'GPLv2'
summary 'Puppet module to install ISPConfig in a LEMP environment'
description 'Puppet module to install ISPConfig in a LEMP environment'
project_page 'https://github.com/meth/puppet-ispconfig/'

dependency 'stdlib'
dependency 'apt'
dependency 'ntp'
dependency 'mysql'
dependency 'php'
dependency 'pureftpd'
dependency 'openssl'
